name: Linting and Testing CI

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on all branches

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r AI/python/requirements.txt
      - name: Run Pylint
        run: pylint --rcfile=AI/python/.pylintrc AI/python/*.py || true
      - name: Run Flake8
        run: flake8 AI/python/ --max-line-length=100

  test-python:
    name: Test Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r AI/python/requirements.txt
      - name: Run Python Scripts
        run: |
          for script in AI/python/*.py; do
            if [[ -f "$script" ]]; then
              echo "Running $script"
              python "$script" || exit 1
            fi
          done